-- user table

# --- !Ups
CREATE TABLE USERS (
        USER_NAME VARCHAR(255),
        USER_EMAIL VARCHAR(50),
        USER_AGE INT,
        USER_ID BIGINT PRIMARY KEY);

CREATE TABLE USER_ACCOUNT (
        USER_ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
        USER_LAST_ACCESS TIMESTAMP,
        USER_STATUS VARCHAR,
        USER_ID BIGINT REFERENCES USERS(USER_ID));

CREATE TABLE USER_ACTION (
        USER_ACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
        USER_ID BIGINT REFERENCES USERS(USER_ID),
        ACTION_MSG VARCHAR(1000));

CREATE TABLE USER_DETAIL (
        USER_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
        USER_ID BIGINT REFERENCES USERS(USER_ID),
        DETAIL VARCHAR(1000));

# --- !Downs
DROP TABLE USER_ACCOUNT;
DROP TABLE USER_ACTION;
DROP TABLE USERS;